### ISSUE TITLE
caddy v2 works?

### ISSUE THREAD

**Issue by kodkuce** [caddy-dns/duckdns#8]
Does this work with caddy v2?  i get error failed to get cert all time

**Comment by mholt** [comment]
It _only_ works with Caddy v2, actually. :) 

Since this issue tracker is reserved for actionable development items, I'm going to close this, but we have a [community forum at caddy.community](https://caddy.community) where more people will be exposed to your question, including people who may be more expert or experienced than I am with the specific issue you're facing. I hope you'll ask your question there. The Help category in the forum even provides a template you can fill out.

If I'm wrong, and this does turn out to be a bug after further investigation, we can reopen this. Thanks for understanding!
